<?php
$tips = [
    "La mayoría de las plantas de interior prosperan con luz indirecta ¡Evita el sol directo para que no se quemen!",
    "Antes de regar, verifica que la tierra esté seca al tacto ¡El exceso de agua puede ser fatal para las raíces!",
    "Usa macetas con buen drenaje para evitar que el agua se acumule y dañe tu planta",
    "¿Sabías que la Sansevieria y el Pothos son excelentes para purificar el aire en casa?",
    "Los posos de café y las cáscaras de plátano son fertilizantes ecológicos para tus plantas",
    "Retira hojas marchitas o amarillas para dar espacio a un crecimiento nuevo y saludable",
    "Gira tus plantas cada semana para que reciban luz de manera uniforme y crezcan equilibradas",
    "El jabón potásico y el aceite de neem son aliados naturales contra plagas como pulgones o cochinillas",
    "El aloe vera no solo es decorativo, sino que también puedes usar su gel para quemaduras leves",
    "Rocía tus plantas tropicales con agua para imitar su entorno natural y mantenerlas felices",
    "Las plantas colgantes son ideales para maximizar el espacio en interiores pequeños",
    "Las suculentas necesitan riego moderado ¡Demasiada agua puede hacer que se pudran!",
    "Coloca un plato con agua cerca de tus plantas tropicales para aumentar la humedad",
    "Evita cambios bruscos de temperatura para proteger tus plantas de interior",
    "Utiliza musgo sphagnum para mantener la humedad en los terrarios",
    "La lavanda es una planta aromática que también repele insectos en el jardín",
    "Evita regar tus plantas en horas de pleno sol para no quemar sus hojas",
    "La tierra bien aireada favorece el crecimiento saludable de las raíces",
    "Agrupa plantas que necesiten condiciones similares de luz y agua",
    "El compost casero es una forma económica y sostenible de fertilizar tus plantas",
    "Las plantas de sombra son perfectas para rincones con poca luz",
    "Limpia las hojas de tus plantas con un paño húmedo para que absorban mejor la luz",
    "Las orquídeas prefieren ambientes húmedos y luz indirecta",
    "El bambú de la suerte puede crecer solo en agua, sin necesidad de tierra",
    "Evita colocar plantas cerca de corrientes de aire o calefactores",
    "El romero es una hierba culinaria que también puedes cultivar en interiores",
    "Las plantas carnívoras requieren agua destilada y un suelo pobre en nutrientes",
    "El cilantro crece rápidamente y es ideal para huertos urbanos",
    "El exceso de abono puede dañar las raíces de tus plantas Usa fertilizantes con moderación",
    "Las begonias son perfectas para añadir color a espacios con sombra",
    "Las plantas aromáticas como el tomillo necesitan mucho sol para prosperar",
    "El riego por goteo es eficiente y asegura que el agua llegue directamente a las raíces",
    "Las plantas en macetas pequeñas necesitan riegos más frecuentes",
    "El cactus es una planta ideal para quienes olvidan regar",
    "El jade es una suculenta que atrae la buena suerte según el feng shui",
    "Usa grava o piedras decorativas para mejorar el drenaje en tus macetas",
    "Las plantas trepadoras como la hiedra son excelentes para decorar paredes",
    "Las raíces aéreas de las epífitas como la tillandsia absorben humedad del aire",
    "El menta es una planta invasiva; cultívala en macetas para evitar que se extienda",
    "Las calatheas tienen hojas decorativas que se mueven según la luz",
    "El sustrato adecuado es clave para el crecimiento de las suculentas",
    "El geranio es una planta resistente y fácil de cuidar",
    "Las plantas de hoja grande requieren más humedad para mantenerse saludables",
    "El bonsái es un arte que requiere paciencia y dedicación",
    "Las plantas colas de zorro son ideales para terrarios cerrados",
    "El jazmín añade un aroma relajante a cualquier espacio",
    "El agua de lluvia es ideal para regar tus plantas, ya que no contiene químicos",
    "Las plantas tropicales como el ficus elastica crecen mejor en ambientes cálidos",
    "El musgo es perfecto para decorar y mantener la humedad en mini jardines",
    "La hortensia necesita tierra ácida para mantener su color vibrante",
    "La albahaca es una hierba culinaria que repele mosquitos",
    "Las plantas acuáticas como los nenúfares embellecen estanques y fuentes",
    "El helecho de Boston es una planta clásica para purificar el aire",
    "La planta del dinero se asocia con prosperidad y crecimiento financiero",
    "El cactus de Navidad florece en invierno y añade color a las fiestas",
    "El chile es una planta productiva y decorativa en el huerto urbano",
    "La planta ZZ es ideal para principiantes por su bajo mantenimiento",
    "Las violetas africanas florecen casi todo el año si reciben luz adecuada",
    "El árbol de jade puede vivir muchos años con los cuidados correctos",
    "El aloe vera ayuda a reducir el estrés al mejorar la calidad del aire",
    "Las plantas como el lirio de la paz filtran toxinas del aire",
    "El bambú negro es una planta elegante para decorar jardines modernos",
    "Los girasoles se inclinan hacia la luz para maximizar la fotosíntesis",
    "La planta araña es ideal para colgar en cestas y purificar el aire",
    "El romero atrae abejas y favorece la polinización en el jardín",
    "La dracaena es resistente y perfecta para interiores con poca luz",
    "El clavel del aire no necesita tierra para sobrevivir",
    "El hibisco florece en verano y embellece cualquier espacio",
    "Las plantas de agua como el papiro aportan frescura a los jardines acuáticos",
    "La gardenia requiere suelos bien drenados y mucho sol",
    "El tomillo limón es una hierba aromática perfecta para cocinar y decorar",
    "El jacinto tiene flores fragantes ideales para interiores",
    "La buganvilla añade un toque tropical con sus colores vibrantes",
    "El diente de león es una planta comestible con múltiples beneficios",
    "El aguacate se puede germinar fácilmente con un hueso y un vaso de agua",
    "La suculenta echeveria tiene hojas gruesas que almacenan agua",
    "El perejil es una hierba versátil y fácil de cultivar en casa",
    "El espatifilo es ideal para decorar y mejorar la calidad del aire",
    "El cactus barril almacena agua en su interior y puede sobrevivir en condiciones extremas",
    "El eneldo es una hierba que crece rápido y es perfecta para condimentar",
    "La salvia tiene propiedades medicinales y es fácil de cultivar",
    "El pensamiento es una flor resistente al frío, ideal para otoño e invierno",
    "Las zanahorias se pueden cultivar en contenedores profundos",
    "La fresa es una planta que puede crecer en macetas colgantes",
    "El trébol de cuatro hojas se asocia con la buena suerte",
    "Las plantas acuáticas ayudan a oxigenar el agua de estanques y acuarios",
    "El pino enano es una planta perfecta para jardines de estilo japonés"
];


// Barajar los tips y concatenarlos
shuffle($tips);
$marqueeText = implode(" &nbsp;&nbsp;<img src='./img/icons/hoja.svg'/>&nbsp;&nbsp;", $tips);
echo "<marquee class='random-marquee' >$marqueeText</marquee>";
?>
